### ISSUE TITLE
Could not find a package configuration file provided by "ICU"

### ISSUE THREAD

**Issue by ChameleonScales** [naelstrof/slop#101]
when running `cmake -DCMAKE_INSTALL_PREFIX="/usr" ./` I get this :
```
-- Found Xrender: /usr/lib/x86_64-linux-gnu/libXrender.so  
CMake Warning at CMakeLists.txt:105 (find_package):
  By not providing "FindICU.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ICU", but
  CMake did not find one.

  Could not find a package configuration file provided by "ICU" with any of
  the following names:

    ICUConfig.cmake
    icu-config.cmake

  Add the installation prefix of "ICU" to CMAKE_PREFIX_PATH or set "ICU_DIR"
  to a directory containing one of the above files.  If "ICU" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring done
-- Generating done
-- Build files have been written to: ~/slop
```

I guess it's problematic because then the `make` command fails :
```
Scanning dependencies of target slopy
[  6%] Building CXX object CMakeFiles/slopy.dir/src/mouse.cpp.o
[ 13%] Building CXX object CMakeFiles/slopy.dir/src/keyboard.cpp.o
[ 20%] Building CXX object CMakeFiles/slopy.dir/src/x.cpp.o
[ 26%] Building CXX object CMakeFiles/slopy.dir/src/slopstates.cpp.o
[ 33%] Building CXX object CMakeFiles/slopy.dir/src/resource.cpp.o
[ 40%] Building CXX object CMakeFiles/slopy.dir/src/slop.cpp.o
In file included from ~/slop/src/framebuffer.hpp:29:0,
                 from ~/slop/src/window.hpp:40,
                 from ~/slop/src/slop.cpp:19:
~/slop/src/shader.hpp:32:21: fatal error: EGL/egl.h: No such file or directory
compilation terminated.
CMakeFiles/slopy.dir/build.make:182: recipe for target 'CMakeFiles/slopy.dir/src/slop.cpp.o' failed
make[2]: *** [CMakeFiles/slopy.dir/src/slop.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/slopy.dir/all' failed
make[1]: *** [CMakeFiles/slopy.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm on Linux Mint

**Comment by naelstrof** [comment]
The missing ICU files just means that Unicode support is limited, but doesn't really affect English users.
The error that's making the build fail is `~/slop/src/shader.hpp:32:21: fatal error: EGL/egl.h: No such file or directory`
I'm unsure which Linux Mint package you need, though it'd probably be called [libegl1-mesa](https://community.linuxmint.com/software/view/libegl1-mesa) or similar.

**Comment by ChameleonScales** [comment]
Thanks ! That solved it (more precisely libegl1-mesa-dev)

**Comment by gregoriochiko** [comment]
I still get the same error message, even after installing `libegl1-mesa-dev`.

**Comment by naelstrof** [comment]
@gregoriochiko Can you post a full error log? You must be missing a different library, or have some other type of problem.

**Comment by AloisMahdal** [comment]
@gregoriochiko Just a random hint: I always do `git clean -xfd` (*destructive* if you have custom uncommitted changes) before re-trying build to ensure that no configs from previous failed build are left over.

**Comment by AloisMahdal** [comment]
BTW here's excerpt from Debian control file (7.3.49 on sid):

    Build-Depends: debhelper (>= 10~)
                 , cmake (>= 3.1.3~)
                 , libegl1-mesa-dev
                 , libicu-dev
                 , libglew-dev
                 , libglm-dev
                 , libxrender-dev
                 , pkg-config

names should be roughly the same for Mint, I guess.

**Comment by ohchiko** [comment]
I think it's done after I try to tidy up my packages, and reinstall the slop and its dependencies. Now it works, thanks for the detailed response.

**Comment by ohchiko** [comment]
Yes, that's the dependencies I need, it's just about the package name and version, thanks.

**Comment by gregoriochiko** [comment]
I think the problem had clear. I tidy up my packages and reinstall slop and its dependencies, and now it works.

Yes, those are the dependencies I need to install, it's just about the package name.

Thanks for the detailed responses.
