### ISSUE TITLE
Permit other locations for shader files

### ISSUE THREAD

**Issue by riri** [naelstrof/slop#113]
Slop enforce all shaders are in the slop configuration directory. As it can be integrated as part of other tools, that would be nice it accepts full paths for shader files reference.

Some packaged tools could provide shaders that wouldn't write in slop directory (maybe with conflicting names). For example a bash script using slop could have its shaders in
`/usr/share/mybashtool/shaders` and then call slop that way:
```sh
slopresult=$(slop -r /usr/share/mybashtool/shaders/myshader)
```

Actually it tries to find `/usr/share/mybashtool/shaders/myshader.vert` and `/usr/share/mybashtool/shaders/myshader.frag` in `$XDG_CONFIG_HOME/slop` (or `$HOME/.config/slop`)

**Comment by naelstrof** [comment]
Wow yeah that should've been implemented at the start. My bad. I was really
focused on providing clean commands, and was thinking of it like you could
"extend" slops functionality by installing more shaders. I'm not super sure
but just so you know I think shaders are searched for in both the users
home directory, then somewhere in /usr. Might help you immediately to know
that.
