### ISSUE TITLE
Is there a way to customize the mouse cursor?

### ISSUE THREAD

**Issue by lucianposton** [naelstrof/slop#127]
While using slop/maim as a color picker, I'd like to set the mouse to a different cursor than the cross e.g. an eye dropper.

Is there a way to do this currently?

**Comment by naelstrof** [comment]
Right now the only way to do that is by editing the source code, you can see the relevant code here: 
https://github.com/naelstrof/slop/blob/903df52bc704e6381f228f5a495842a17ef4b4fa/src/slopstates.cpp#L100

And here:
https://github.com/naelstrof/slop/blob/903df52bc704e6381f228f5a495842a17ef4b4fa/src/mouse.cpp#L33

**Comment by lucianposton** [comment]
Thanks.

Looks like xlib doesn't have an eyedropper in their default cursor font, unfortunately. https://tronche.com/gui/x/xlib/appendix/b/ . And, adding a way to load a custom cursor font or pixmap, isn't worth the time for this minor feature imo, so I'll close the issue for now.

**Comment by naelstrof** [comment]
It's a lot closer than you'd think to being implemented, with the OpenGL mode it has full shader compiling with some hard-coded parameter bindings. (set here: https://github.com/naelstrof/slop/blob/903df52bc704e6381f228f5a495842a17ef4b4fa/src/glrectangle.cpp#L224)

If there was a parameter to set up a custom texture sampler, slop could load in an image and overlay it via shader on the mouse position.

You'd have to do some shader and OpenGL shenanigans though-- namely you'd have to send OpenGL the texture, set its mode to clamped, then modify one of the shaders to have an bindable sampler2D.

The shader would have to do some of its own blending operations as well. This shader is a good start, though it uses a bunch of nasty if functions.

https://github.com/naelstrof/slop/blob/master/shaderexamples/crosshair.frag

**Comment by naelstrof** [comment]
You would need to know a lot about image loading, OpenGL, and shaders though. Feel free to bug me if it's really important to you, though using the built-in eyedropper is a much better solution than what I suggested lmao.
