### ISSUE TITLE
Persisten slop for recording

### ISSUE THREAD

**Issue by betovidal** [naelstrof/slop#132]
I was wondering if it's possible to leave the recording selection visible until recording stops. I was amazed of how easy it is to implemenet a recording script but it can be complicated if the recording target is a region instead of a window.

By the way, I'm loving slop.

**Comment by naelstrof** [comment]
Glad you're loving it! Unfortunately I didn't set up any options to allow it to just display the selection... slop is just a window so I was concerned about how it'd eat people's input or get re-organized behind other windows if it didn't close immediately when finished.

You could consider sending desktop notifications for notifying the user that the script is recording or something similar: https://wiki.archlinux.org/index.php/Desktop_notifications

**Comment by BanchouBoo** [comment]
If you're using ffmpeg you can use `-show_region 1` instead

**Comment by betovidal** [comment]
Thanks a lot @BanchouBoo! That's exactly what I needed. I forgot to close this issue as it's not related to slop. Hopefully more people will find it useful.
