### ISSUE TITLE
Using the "magnifying glass" (based on shaderexamples) to select a pixel

### ISSUE THREAD

**Issue by fboumol** [naelstrof/slop#139]
I am trying to select a pixel using the magnifying glass described in the readme page as:
 - slop -r crosshair | ~/.config/slop/crosshair{.frag,.vert}

Is it possible to add some parameter to the previous command to get in the standard output the info of a selected pixel?. 

I am wondering about the previous issue because I am interested to combine the magnifying glass (provided by slop) with [grabc](https://github.com/muquit/grabc)

PS: As a side remark let me say that the code of the magnifying glass is although working complaining about the following:
  "bash: /home/myuser/.config/slop/crosshair.frag: permission denied"
I do not understand what it is going on with this complain.

**Comment by naelstrof** [comment]
All shaders attempt to load from your user directory, if that fails it falls back onto preincluded ones.

As for making slop select only a pixel, you'd just have to add `-t 0` to your command.

**Comment by fboumol** [comment]
> All shaders attempt to load from your user directory, if that fails it falls back onto preincluded ones.

So, I understand that there is no standard way to get rid of such complain message.

> As for making slop select only a pixel, you'd just have to add -t 0 to your command.

It is clear that `slop -t 0` is the way to get in the standard output the pixel information. But in my case I am not getting anything in the standard output when I run (I guess due to the shader)
`slop -t 0 -r crosshair | ~/.config/slop/crosshair{.frag,.vert}`.

Indeed, when I run `slop -r crosshair | ~/.config/slop/crosshair{.frag,.vert}` I neither get in the standard output any information.

**Comment by naelstrof** [comment]
Oh dear! Sorry I totally misread your message. 
The readme is totally misleading! At the top it does say `The files listed to the right of the | are the required files for the command to the left to work correctly.`
It's not meant to be piped like that, `slop -t 0 -r crosshair` should work fine!

**Comment by fboumol** [comment]
Oh my god, now everything makes sense (the bash complain, why nothing on standard output, etc). As you have guessed I was reading all the time the symbol `|` as a pipe.

Thank you. For a future version of the readme I suggest you use a different symbol for comments.
