### ISSUE TITLE
Selection cancels immediately when called by i3 keybinding

### ISSUE THREAD

**Issue by Streetwalrus** [naelstrof/slop#25]
I just found out about maim, however I'm facing a problem with slop itself. I know this much : 
-Any nested call to slop faces the same issue, be it a direct call, maim -s or even a script.
-Only i3 keybindings are affected, so if I add something like exec_always slop to my config then restart i3, I do get the slop window. It also works with dmenu or when called from a terminal.
-Running it with something like urxvt -e maim -s in my script does work but it spawns a new terminal which is disturbing.

I get the following output :
```
X=0
Y=0
W=0
H=0
G=0x0+0+0
ID=0
Cancel=true
```

I can retrieve any other info you might need. I run Arch Linux and the problem happens with both the latest version from the -git AUR package and the version in official repos (3.1.15).

**Comment by naelstrof** [comment]
Have you tried increasing --gracetime to a higher value?
Something like `maim -s -g=4` might solve your issue, otherwise I'll try to see what's going on.

**Comment by Streetwalrus** [comment]
I enabled --nokeyboard to no avail. So unless --gracetime does more stuff I'm sure it's not that.

**Comment by Streetwalrus** [comment]
Update : mapping the same shortcut I was using (the issue was combination-independent) with xbindkeys instead works perfectly fine, so I'll use that as a temporary workaround (or even switch entirely to it for non-i3 bindings).

**Comment by naelstrof** [comment]
When I went to test slop in i3, I couldn't get it to run at all via bindings. i3 launches slop in a way that it couldn't grab the mouse cursor (which is critical to function).

I'm going to have to play with it more, but the problem isn't easily solvable for now.

**Comment by Streetwalrus** [comment]
Thanks for checking it out, as I said I have found a workaround so it's nothing urgent.

**Comment by naelstrof** [comment]
Could you try the new tag v4.1.16?
I successfully got slop working correctly on i3.

The problem was (for me at least) that i3 grabs the mouse whenever you're holding a key that belongs to a key combination (usually the $mod key). So when I would press the key combination to launch slop, it would fail immediately due to it being launched while the mouse was being grabbed.

Slop now repeatedly tries to grab the mouse for the duration of --gracetime until it succeeds, which is plenty of time for someone to release the key combo, releasing the mouse.

**Comment by Streetwalrus** [comment]
Works perfectly fine here. I guess that closes the issue.

**Comment by naelstrof** [comment]
Sweet, thanks for reporting this!

Make another issue if you have any other problems or requests.

**Comment by Streetwalrus** [comment]
No problem. I permanently switched to sxhkd in the meantime but I'm glad I could help.
