### ISSUE TITLE
Flag to output geometry directly

### ISSUE THREAD

**Issue by wavexx** [naelstrof/slop#26]
I often use slop with other X utilities, and I generally end up doing `slop -f '%g'` so frequently that I feel the default behavior (no flags) or `slop -g` should have been to "output geometry" _directly_.

Maybe it's too late now to change default behavior, but having `-G`, for instance, would still be useful in my opinion.

**Comment by naelstrof** [comment]
Use an alias in your ~/.bashrc.
Something like `alias slop="slop -f '%g'"`
You're probably right that it should've been default behavior, but slop didn't even have geometry support in early versions, and I believe it's too late to change it now.

**Comment by naelstrof** [comment]
If you want to make your own branch of slop that does this specifically, it's pretty easy to change.
* Make sure you have gengetopt on your system.
* Then do this in a terminal:
```bash
git pull git@github.com:naelstrof/slop.git
cd slop
git checkout -b geometry
```
* Then replace [these lines](https://github.com/naelstrof/slop/blob/master/CMakeLists.txt#L57) in CMakeLists.txt with:
```c++
    execute_process( COMMAND "${SED_EXECUTABLE}" "-i" "0,/REPLACEME/{s/REPLACEME/%g/}" "cmdline.c"
                    WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src" )
   # Then replace remaining instances.
    execute_process( COMMAND "${SED_EXECUTABLE}" "-i" "s/REPLACEME/%g/" "cmdline.c"
                     WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src" )
```
It will set the default action to output %g. (It's messy as hell because it's a workaround of a bug in gengetopt, sorry.)
* Then finally compile, install, and test it.
```bash
cmake ./
make
sudo make install
slop
```

**Comment by wavexx** [comment]
On 06/21/2015 09:05 PM, Dalton Nell wrote:
> Use an alias in your ~/.bashrc.
> Something like `alias slop="slop -f '%g'"`

I already have an alias for that, but aliases are not really useful when
used in scripts, especially when scripts are meant to be distributed.

> You're probably right that it should've been default behavior, but
> slop didn't even have geometry support in early versions, and I
> believe it's too late to change it now.

An usual hack in these cases, if you're favorable to changing default
behavior, is to create an hardlink during install and check for the
executable name. When invoked as 'slop2' (or something else), change the
default behavior.

If not, I would still favor a short flag for "output geometry".

**Comment by wavexx** [comment]
On 06/21/2015 09:19 PM, Dalton Nell wrote:
> If you want to make your own branch of slop that does this specifically, it's pretty easy to change.

It's not really a problem for me specifically. I currently use a small
wrapper and I'm done with it.

I only reported this because I think that geometry specs are pretty
consistent for X11 programs in general. slop is one of the "missing core
X11 utilities" IMHO, and I'd love it to play nice by default.

**Comment by naelstrof** [comment]
This will be considered for default behavior for slop-wayland.
