### ISSUE TITLE
I can't compile it, problem with GLEW

### ISSUE THREAD

**Issue by introlinux** [naelstrof/slop#30]
The output:

cmake -DCMAKE_OPENGL_SUPPORT=true ./
-- Regenerating cmdline.in
CMake Error at CMakeLists.txt:109 (find_package):
  By not providing "FindGLEW.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GLEW", but
  CMake did not find one.

  Could not find a package configuration file provided by "GLEW" with any of
  the following names:

    GLEWConfig.cmake
    glew-config.cmake

  Add the installation prefix of "GLEW" to CMAKE_PREFIX_PATH or set
  "GLEW_DIR" to a directory containing one of the above files.  If "GLEW"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by naelstrof** [comment]
What version of CMake are you using and on what linux distribution?

CMake ships with its own FindGLEW, since version 2.8.10. Depending on your answer I'll probably have to just include a FindGLEW.cmake in the project.

**Comment by introlinux** [comment]
I updated cmake and all went perfect!
Thanks.

**Comment by pixelastic** [comment]
Sorry to bump a closed issue but here is the errored output I got when running `cmake -DCMAKE_OPENGL_SUPPORT=true ./`

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Warning: Command gengetopt or sed not found! Won't regenerate command line code. (If you're just compiling this doesn't matter.)
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found GLX: /usr/include
-- Could NOT find Xrender (missing:  XRENDER_LIBRARY XRENDER_INCLUDE_DIR)
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148(message):
  Could NOT find GLEW (missing: GLEW_INCLUDE_DIR GLEW_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindGLEW.cmake:44 (find_package_handle_standard_args)
  CMakeLists.txt:126 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/tim/local/src/slop/CMakeFiles/CMakeOutput.log".
```

I'm using `cmake version 3.5.1` on Ubuntu 16.04. As per your comment, I should have a cmake version able to find glew on its own, but it is still failing.

**Comment by pixelastic** [comment]
Nevermind, I just did not `sudo apt-get install libglew-dev` before.

I still have other dependency issues, but I'm fixing them one by one.
