### ISSUE TITLE
Extra pixel(s) when using slop with maim.

### ISSUE THREAD

**Issue by onodera-punpun** [naelstrof/slop#34]
https://github.com/naelstrof/slop/commit/a8f1e5cd57bbb8cdda75c529b48eb5b9949567f3 introduced a bug with openbox for me, it actually ads a useless pixel, example; https://sr.ht/EGgN.png

**Comment by naelstrof** [comment]
Sorry about that, didn't thoroughly think that through or test it. I was rushing it out for a friend.

Now we shouldn't have anymore off-by-one bugs-- hopefully.
