### ISSUE TITLE
Border animation drawn in screenshots with xcompmgr

### ISSUE THREAD

**Issue by sigzegv** [naelstrof/slop#39]
Using region selection with xcompmgr active catches the closing border animation.

example : http://imgur.com/CCjOQPW

**Comment by naelstrof** [comment]
You have to add the window class "slop" to the window animation's exception list.

Wherever the window animation comes from I mean, slop doesn't have control of those animations or a way to detect them.

**Comment by woodruffw** [comment]
Sorry for necroposting here, but I'm having the same problem with i3/compton.

Any tips on fixing this? My compton invocation is `compton -fCGb -D 8 -m 0.8 --backend glx --vsync opengl`.

**Comment by naelstrof** [comment]
You'll have to add slop to the exceptions list of compton.

You can find how to do that here:
https://wiki.archlinux.org/index.php/Compton#Disable_shadowing_of_some_windows
