### ISSUE TITLE
The screenshot with region selection behaves weird under i3wm

### ISSUE THREAD

**Issue by lianxiangru** [naelstrof/slop#40]
This behavior seems to rise recently. See the figure:
![ss](https://cloud.githubusercontent.com/assets/8991941/14516828/fa21450e-01d4-11e6-85f7-a5b9f4789f4b.png)
while the window should be like (which is from maim without using region selection)
![ss](https://cloud.githubusercontent.com/assets/8991941/14516846/2bff71d6-01d5-11e6-94e7-1259fd921b42.png)
The happens even without a composer.

**Comment by naelstrof** [comment]
Try using the --opengl mode, slop doesn't actually clear the color of the inner window. Which is dumb, sorry. Default slop is at the mercy of X whether it has junk pixels in it, but clearing the entire window using pure x11 is incredibly slow so I simply don't do it.

--opengl mode is hardware accelerated where I do clear the screen every frame, you'll need slop compiled with it enabled.

You can also use neato shaders with it.
```
slop --opengl --shader hippie
```

**Comment by lianxiangru** [comment]
@naelstrof It works! Thank you!
