### ISSUE TITLE
ID returned is incorrect (or useless)

### ISSUE THREAD

**Issue by AloisMahdal** [naelstrof/slop#41]
I want to use slop to select window that I further want to close using wmctrl, but the ID returned by slop seems to be incorrect; I tried to use it with wmctrl but it closes wrong windows or nothing (seemingly).

Other tools like wmctrl (`wmctrl -l`) or xwininfo return another number (don't want to use them as their interactive mode is none or inferior to slop); slop seems to be the odd one here.  Or maybe I just don't understand it correctly, in which case it would be nice to document it somewhere.

**Comment by naelstrof** [comment]
Could you try the -n option?
```
-n, --nodecorations           Attempt to select child windows in order to
                                  avoid window decorations.  (default=off)
```
It doesn't say so, but this affects the window ID selected. Slop tries to select the highest level of window available that still contains the mouse unless -n is enabled. Window managers typically have each window in some kind of window container, which slop tries to select.

Could you also tell me which window manager or desktop environment you're using?

**Comment by AloisMahdal** [comment]
Thanks, that works!

The environment is i3 4.12-31-g0e29101 (built from source) on Fedora 23; [config here][1].

  [1]: https://github.com/AloisMahdal/mydots/blob/master/dotfiles/i3/config
