### ISSUE TITLE
urxvt under i3 not reported properly

### ISSUE THREAD

**Issue by AloisMahdal** [naelstrof/slop#42]
I'm using slop inside a script on Fedora 23 under i3 to select window that I further close using `wmctrl`. I've been doing this for few days now.  With most windows it works fine.

Unfortunately not with urxvt.

When I try to select urxvt, it seems as if an invisible window lays over actual urxvt window, taking up almost all space, except thin (few pixels) strip near bottom border.  When I manage to avoid the invisible window (which is kinda cumbersome), it works fine and urxvt gers closed, otherwise nothing happens (wmctrl just ignores the attempt).

Further observations:
-  In hexadecimal, the overlay window always has ID like `0x??0000a` while the correct window
  has `0x??0000f`, i.e. the last digit seem to be always 'a' and 'f'.
-  Other tools (`wmctrl -l`, `xwininfo`, `xdpyinfo` and `xdotool selectwindow`) always show just the
  correct window and never the overlay.
-  `xprop -id` shows nothing for the overlay, normal output for the correct window.
-  the size of the overlay is always multiple of line height, so the strip may be zero.
-  One application that seems to have similar problem is Opera ... the legacy proprietary
  opera-12.16 (The hex IDs are 3c00005 for correct window, 0x3c00011 for overlay; and
   xprop shows only `XdndAware(ATOM) = BITMAP` for overlay).

**Comment by naelstrof** [comment]
Try `slop -n`.

**Comment by naelstrof** [comment]
It's an issue with slop's window decoration detection, slop always climbs up the window higharchy until it finds the window right before root. Windows that don't follow this convention cause problems. To fix this i'd have to pick apart xprop's source code I suppose.

**Comment by AloisMahdal** [comment]
What I'm running exactly is `slop -n -f "%i"`

**Comment by naelstrof** [comment]
Once finals week is over I should be able to work on this, sorry for any inconveniences...

**Comment by naelstrof** [comment]
Should be fixed with https://github.com/naelstrof/slop/tree/slop-release-candidate, could you report if it's better?

**Comment by AloisMahdal** [comment]
I'd be happy to, but the version you mentioned crashes immediately:

    @fullmoon:~!1!$ slop 
    Slop encountered an error:
    The file or folder textured.vert was not found in either /usr/share/slop/ or /home/amahdal/.config/slop/

    @fullmoon:~!1!$ 

slop-release-candidate does not contain instructions so I used those from master, which seemed to work (save for few extra warning)...

**Comment by naelstrof** [comment]
Could you pull and try again? I've removed the file dependencies entirely.

**Comment by AloisMahdal** [comment]
From ebd1b98:

    slop: error while loading shared libraries: libslopy.so: cannot open shared object file: No such file or directory

I actually tried to build it two days ago (~half a day after your last comment) and I got a different, still bad behavior: whole screen got black and I just saw the slop's rectangle. I was not able to report that since I had other urgent work to do. (OTOH since your RC branch seems to change unpredictably, it's hard to say if it was even relevant to this issue.)

**Comment by naelstrof** [comment]
Yeah, my bad. You'll have to `make install` or move the library into the same directory as your current directory.

The black screen is probably due to i3 not recognizing that the window is supposed to be transparent.

Could you describe your environment so I can replicate the issue?

(Sorry I basically need a tester for the RC.)

**Comment by AloisMahdal** [comment]
Well, the last attempt was after `sudo make install`, so apparently it did not help.

I'll try it again after copying the lib. Stay tuned...

Regarding the environment, it's Fedora 24 with urxvt from Fedora repos and i3 built localy from [upstream][1].  My [i3][2] and [urxvt][3] configs (the latter I actually merge by includes on .Xdefaults so the copnfig might not work for you, OTOH my guess is even plain urxvt might replicate it) are both here on github.

  [1]: https://github.com/i3/i3/tree/7785e7be7dae5c8de4fb300b125e0e0f751392f9
  [2]: https://github.com/AloisMahdal/mydots/blob/master/dotfiles/i3/config
  [3]: https://github.com/AloisMahdal/mydots/blob/master/dotfiles/config/Xlib/global.Xdefaults

**Comment by AloisMahdal** [comment]
OK, so make install puts libslopy.so under /usr/local/lib, which apparently is not loaded. I'm not sure how to debug ld problems, [one answer on SO invloving ldconfig][1] shows it should not, [another one with ld][2] shows it should.

  [1]: http://stackoverflow.com/a/10526145/835945
  [2]: http://stackoverflow.com/a/21610523/835945

Simply running slop from the same directory as is libslopy.so does not work, Anyway, `LD_PRELOAD=$PWD/libslopy.so` slop does.

Back to the issue: I retried and the screen is [still black][3]. Also I tried to use the id and it does not work. It's basically the same as when i originally reported it: unless I manage to avoid the "ghost window" (which means selecting roughly 1px high margin), I get 0x220000f, use it with xclose but nothing is closed.

    [3]: http://file.vornet.cz/tmp/slop-black/

**Comment by AloisMahdal** [comment]
Oh, and regarding my i3/config, I realized if you are going to try it. you need to know keyboard shortcuts:

 *  press `Win+Enter` to open urxvt,
 *  press `Win+Delete` to close current window,
 *  press `Win+Shift+Delete` to close whole session (need to confirm using mouse).

**Comment by naelstrof** [comment]
Thank you, this is incredibly helpful!

Cmake's default install prefix is /usr/local, next time you can just do
``` sh
cmake -DCMAKE_INSTALL_PREFIX=/usr ./
make
sudo make install
```
I probably should've pointed that out. Thanks again!

**Comment by naelstrof** [comment]
OK. I realized it's black because you're not running a compositor!
I've added detection for this, and slop will fallback to the xshape extension if you're not running one. It should all be fixed now.

**Comment by AloisMahdal** [comment]
I'm always happy to help, I really like idea behind slop and I do use it evey day! :)

Regarding the install, no problem, I can go with using LD_PRELOAD.

Also, your conpositor fix works, now indeed slop behaves normally; no black screen.  Regarding the fix, though, I get 2 messages to stderr:

    Failed to detect a compositor, OpenGL hardware-accelleration disabled...
    Failed to launch OpenGL context, --shader parameter will be ignored.

Now, is it necessary to print these?  If I'm not running compositor, I should be aware of it and I guess it's of little use.  The second one seems related, but at any rate, I'm not using --shader option so it should work.

The thing is, I'm using slop in a script that will present any stderr as desktop notification; it's meant to only display real error, otherwise it would quickly become annoying.  I guess these messages could be useful in some verbose mode, though.

**Comment by AloisMahdal** [comment]
Now, back to the topic, the urxvt problem seems to be the same as I originally reported.

**Comment by naelstrof** [comment]
Should be fixed with https://github.com/naelstrof/slop/commit/03a2956e47a8d2c1b1d865a6b3cdce97aa60bdad

You'll have to run slop with the parameters `slop -n1 -f%i` to get a first level child of a window like you intend.

-n2 now has the original behavior (really aggressive child window selection.)

**Comment by naelstrof** [comment]
I added a --quiet option as well, to silence warning messages.

**Comment by AloisMahdal** [comment]
Nice!  So with 4db2dbc, this works for me:

    slop -q -n1 -f "%i"

I feed the output into wmctrl, which will close the correct window.  This works for all windows, ie. also urxvt and opera.

**Comment by naelstrof** [comment]
That's great! Glad it works now for you.
