### ISSUE TITLE
Error compiling on Ubuntu Minimal 16.04

### ISSUE THREAD

**Issue by Joaquin-V** [naelstrof/slop#44]
This is cmake's output:

```
Warning: Command gengetopt or sed not found! Won't regenerate command line code. (If you're just compiling this doesn't matter.)
FindIMLIB2.cmake: imlib2-config not found. Please set it manually. IMLIB2_CONFIG=IMLIB2_CONFIG-NOTFOUND
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenGL.cmake:172 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:109 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by naelstrof** [comment]
It appears you don't have the dependencies. Install imlib2 and mesa (or your system's equivalent). Nvidia/amd supplies opengl stuff as well.

**Comment by pixelastic** [comment]
FWIW, I fixed this issue with `sudo apt-get install libpng-dev libimlib2-dev` on Ubuntu 16.04.

I now have another `Could NOT find GLEW` error, though.

**Comment by pixelastic** [comment]
Here is the list of dependencies I had to install for `cmake` to succeed. Hope it will help another Ubuntu user:

```
sudo apt-get install libxext-dev
sudo apt-get install libpng-dev
sudo apt-get install libimlib2-dev
sudo apt-get install libglew-dev
sudo apt-get install libxrender-dev
sudo apt-get install libxrandr-dev
```

**Comment by smag501** [comment]
sudo apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake ..

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/miner_org/xmrig/build/CMakeFiles/CMakeOutput.log".
miner@simpleminer:/root/miner_org/xmrig/build$

what's the problem?
