### ISSUE TITLE
"User pressed key. Canceled selection" while no keys are pressed

### ISSUE THREAD

**Issue by s0r00t** [naelstrof/slop#45]
Arch x64 here, latest i3 + latest slop from the repos.

When I run slop (w/out maim), after the gracetime period, it automatically closes itself, claiming that a key was pressed although none was.

**Comment by sliceofcode** [comment]
Also getting this, on multiple DEs, with `maim -s`. Don't really know why it happens.

**Comment by chrjguill** [comment]
I've figured out that this happens whenever `steam` is running. Once steam has been killed, slop performs fine.

I'm not sure why this is or what it's detecting, since `xev` isn't returning any keypresses when I focus it.

**Comment by robinlandstrom** [comment]
I had the same problem, added some debug output to x.ccp and started pressing keys on the keyboard to see the keycodes change...

Result: X though my F10/VolumeUp  key was stuck in pressed state, after pressing it with and without the fn hutton pressed slop runs and detects keypresses as expected.

```
diff --git a/src/x.cpp b/src/x.cpp
index a650ee5..0bb144b 100644
--- a/src/x.cpp
+++ b/src/x.cpp
@@ -19,6 +19,8 @@
  */
 #include "x.hpp"
 
+#include<iostream>
+
 slop::XEngine* xengine = new slop::XEngine();
 
 int slop::XEngineErrorHandler( Display* dpy, XErrorEvent* event ) {
@@ -158,7 +160,8 @@ bool slop::XEngine::anyKeyPressed() {
     // Every bit should be 0 if nothing is pressed.
     for ( unsigned int i = 0; i < 32; i++ ) {
         if ( keys[ i ] != 0 ) {
-            return true;
+           std::cout << "Byte array: " << i << " is " << (int)keys[i] << "\n"; 
+            //return true;
         }
     }
     return false;
-- 
2.10.2
```

**Comment by naelstrof** [comment]
Should be fixed with https://github.com/naelstrof/slop/tree/slop-release-candidate. Could you tell me if the issue persists?

**Comment by sliceofcode** [comment]
@naelstrof Yes. It also works excellently.

**Comment by naelstrof** [comment]
Thanks for the feedback!

**Comment by rivertam** [comment]
I'm encountering this today... Steam isn't running and I'm on the most recent version of slop (at least on apt): 4.2.20. I've been using slop for like a year so far and I've had no issues (and I've used it in a lot of contexts and it's been really resilient).

I'm calling `slop -f "%g"`
