### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by anarcat** [naelstrof/slop#49]
This package is now in [NEW][], which means it is in the proces of entering the [Debian][] archive. This can take some time, depending on the size of the package. Once the NEW process is completed, it takes about 10 days for the package to trickle down into "testing", which will become the next Debian release.

[Debian]: https://debian.org/
[NEW]: https://ftp-master.debian.org/new.html

This means your package will end up being part of Debian "stable" soon. If you want to add features or fix bugs for the current packaged version (4.3.21), it would be important to make a release shortly otherwise an old version may be stuck in debian stable for a while (2-3 years). A typical Debian release, according to [those historical statistics][]:

[those historical statistics]: https://wiki.debian.org/DebianReleases#Production_Releases

* endures a freeze cycle of 7 +/- 1 months before getting released.
* is released about 2 years after the previous one (the often cited example of Debian Sarge being quite an exceptional event in Debian history).
* leaves users about 1 year to upgrade to the next one once this latter itself gets released.
* has (from release to the end of security updates) a total lifetime of about 3 years.

The [next freeze][] is scheduled in february 2017 which gives an expected release date for the next stable around Q4 2017, which would mean main support until 2020 and extended LTS until 2022.

[next freeze]: https://release.debian.org/

The source code of the debian package is in the `debian` branch in [collab-maint][]. You can merge it here directly and take over maintainership, in which case you will need a sponsor to upload new versions into Debian, which I am happy to do. Otherwise I will continue maintaining it separately and watch for new releases here and you have nothing special to do.

[collab-maint]: https://anonscm.debian.org/git/collab-maint/slop.git/log/

This is a purely informative ticket and you may close it as you see fit. You may also follow progress on the Debian packaging effort in [the ITP #842974](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842974).

**Comment by naelstrof** [comment]
Wow awesome, good to know. Thanks!

**Comment by anarcat** [comment]
yes, sorry to mention that slop is in debian (including the upcoming stretch release).

https://tracker.debian.org/pkg/slop

don't hesitate to let me know if there's any question or issues with the debian package, either here, through the Debian BTS or my @debian.org email address.

congratulations!
