### ISSUE TITLE
Failed to grab keyboard

### ISSUE THREAD

**Issue by zestyr** [naelstrof/slop#60]
After recently updating slop, I can no longer trigger it using sxhkd.
I get the following error:
```
Slop encountered an error:
Failed to grab keyboard.
```

This also happens when using the `--nokeyboard` argument.

slop v5.3.28, sxhkd 0.5.7, bspwm 0.9.2, Arch Linux

**Comment by zestyr** [comment]
Hmm, this also happens with `scrot -s`
```
giblib error: couldn't grab keyboard:Resource temporarily unavailable
```

I guess it isn't an issue with slop then.

**Comment by naelstrof** [comment]
No it is, I need to keep slop from crashing since it's non-fatal. I'll let you know when I fix it.

**Comment by zestyr** [comment]
Oh sweet, thanks. If I insert a `sleep 0.2` before calling slop, it works, so I guess sxhkd isn't ungrabbing fast enough. I guess slop could wait for that?

**Comment by naelstrof** [comment]
Oh whoa, I never knew about that. I could make slop retry grabbing for a second or so, but that'd make slop really unresponsive imo.

You can always cancel a selection, even if it fails to grab the keyboard. It'll just let input fall through if so.

Could you try this new release? It should be fixed: https://github.com/naelstrof/slop/releases/tag/v5.3.29

**Comment by naelstrof** [comment]
Sorry, this release, not that one: https://github.com/naelstrof/slop/releases/tag/v5.3.30

**Comment by zestyr** [comment]
Works now, starts immediately and I'm able to cancel pretty much instantly.
Thanks for fixing it!

**Comment by Streetwalrus** [comment]
Looks like there are still issues on i3, slop doesn't crash but doesn't really work either, it draws the border around the window I'm currently hovering and prevents me from clicking anywhere until I start typing.

**Comment by naelstrof** [comment]
It seems to work fine for me. What kind of configuration do you have for i3?

**Comment by Streetwalrus** [comment]
https://github.com/Streetwalrus/dotfiles/blob/master/i3/config#L106

I can reproduce consistently with just `slop` as the command.

**Comment by naelstrof** [comment]
Ok confirmed, copying your configuration I get the same issue. I'll try to figure out what's going on.

**Comment by naelstrof** [comment]
So slop was just failing to grab the mouse, failing to grab is now fatal, and now slop tries repeatedly for .5 seconds after launching before fatally shutting down.

Tested and fixed in https://github.com/naelstrof/slop/commit/3634e20f0ea85c6b046b4df0b18d8b42ae430741

**Comment by Streetwalrus** [comment]
Can confirm it's working now. Thanks.
