### ISSUE TITLE
Seems to run from terminal, but not from XFCE's keyboard daemon

### ISSUE THREAD

**Issue by supercheese200** [naelstrof/slop#61]
Using slop from xfce's keybinding menu has no effect.

Sample: 
![20170225-18-00-26](https://cloud.githubusercontent.com/assets/4404985/23333501/699b3ea4-fb84-11e6-91af-9a73c7633a90.png)

This has no effect, and does not prompt with any selection menu.

However, running from a terminal is fine.
![20170225-18-01-48](https://cloud.githubusercontent.com/assets/4404985/23333505/7d3e519e-fb84-11e6-9c09-0830cfe9f6af.png)

Slop *does* run, however, if I execute 'termite -e slop' from XFCE bindings.

I am using Arch Linux's latest package version (5.3.28).

**Comment by supercheese200** [comment]
Building from git (master) didn't seem to fix the issue.

**Comment by naelstrof** [comment]
It's due to slop crashing from failing to grab the keyboard. https://github.com/naelstrof/slop/issues/60

I'll let you know when it's fixed.

**Comment by naelstrof** [comment]
Should be fixed with this release: https://github.com/naelstrof/slop/releases/tag/v5.3.29

Could you inform me if this issue is fixed?

**Comment by supercheese200** [comment]
Slop changes the cursor, immediately exits, and the cursor is reverted.

**Comment by supercheese200** [comment]
If I set the keybind to `bash -c sleep 0.1; <screenshot script utilizing slop>`, it works. I believe the issue is caused by XFCE executing the command before relinquishing keyboard control.

**Comment by naelstrof** [comment]
Does the same thing happen if you run slop with --nokeyboard?

**Comment by supercheese200** [comment]
Yes.

**Comment by naelstrof** [comment]
The newest slop already has some pretty comprehensive checks to make sure that a key was pressed down from an unpressed state.

It would help if you checked your system logs to see what kind of error message is output. It may be crashing for a different reason.

**Comment by naelstrof** [comment]
I'll try replicating the issue, thanks for helping.

**Comment by naelstrof** [comment]
OK. I've replicated, then fixed the issue. Should be fixed for real this time: https://github.com/naelstrof/slop/releases/tag/v5.3.30

Sorry for the inconvenience.

**Comment by supercheese200** [comment]
Works.

**Comment by naelstrof** [comment]
Thanks!

**Comment by hansfn** [comment]
Sorry about this slightly off-topic question, but I couldn't find a good answer for it. 

How do you display/capture the output from slop when run as a XFCE keyboard shortcut? The only "solution" I can think about is creating a small script that runs slop and sends the result to for example notify-send or xsel. 

Running slop as a keyboard shortcut still works with version 7.4 which is good :smile:

**Comment by AloisMahdal** [comment]
Well I'd say it's totally off-topic and it's more related to xfce than slop so maybe you would have better luck at `#xfce` at freenode etc. :-)

*sshhh... depends on what you mean by "display/capture" (as in "where you want the output displayed/captured) but anyway the solution with script is pretty much what I'd do.*
