### ISSUE TITLE
Magnify mode

### ISSUE THREAD

**Issue by zestyr** [naelstrof/slop#62]
I was really enjoying the experimental OpenGL magnifying mode, which seems to have been removed recently. Any plans of bringing it back?

**Comment by naelstrof** [comment]
The plans are to make the shader system robust enough to allow for that. It's not quite implemented yet.

The idea is that shaders would have access to a desktop image, the screen size, cursor location, select region-- and anything else that it might need to draw the magnification itself.

Unfortunately that hasn't been implemented yet. Sorry for removing the feature! If you still need it immediately, you'll have to downgrade slop for now.

**Comment by zestyr** [comment]
Alright, sounds pretty good. It wasn't a necessity so I'll stay updated. 
Thank you for your great work on maim and slop, it's a really great combination.

**Comment by naelstrof** [comment]
Alright it's done, check out https://github.com/naelstrof/slop#shaders for the "crosshair" shader.

**Comment by zestyr** [comment]
Amazing, thanks!
