### ISSUE TITLE
Compton applies transparency effects on the entire screen during selection

### ISSUE THREAD

**Issue by jclc** [naelstrof/slop#68]
Hey, I figured what was causing the blurring issue I mentioned in issue #67; it wasn't slop's effect but in fact my compositor's effect that is applied on transparent GUI elements, such as drop-down menus, the Xfce4 launcher and transparent terminal windows. If you think this is Compton's issue rather than slop's, feel free to close the issue.

https://gist.github.com/jclc/eda606982b8083899c1987eb4ad3a252
I'll post my compton.conf file here in case it'll be useful. The effect itself is `blur-kern = "3x3box"`.

**Comment by naelstrof** [comment]
I haven't tested yet, but adding slop to Compton's exception list might solve the issue

**Comment by jclc** [comment]
Yeah, alright. That was a pretty easy fix. I should've figured that out on my own.

**Comment by naelstrof** [comment]
Thanks for the feedback!
