### ISSUE TITLE
Wait for the window to be destroyed before returning

### ISSUE THREAD

**Issue by Streetwalrus** [naelstrof/slop#69]
`maim -s -l` often ends up having the highlight overlaid in the screenshot, I'm pretty sure this didn't happen before the recent refactor. It would be a good idea to wait for the slop window to be fully destroyed before handing control back.

**Comment by naelstrof** [comment]
I'm assuming you're not using OpenGL acceleration? OpenGL does do a double buffer clear before exiting.

Though I should add the event handling for those who don't use OpenGL. I'll get on it.

**Comment by Streetwalrus** [comment]
I'm pretty sure I'm using opengl, since it's on by default and I have compton running. For now `-d 0.1` seems to do the trick.

**Comment by naelstrof** [comment]
Should be fixed with 170a6d0a8016768caafe2400ef159df024ff69ec
Let me know if it works!

**Comment by Streetwalrus** [comment]
Seems to work, thanks.
