### ISSUE TITLE
error: GLSL 1.30 is not supported

### ISSUE THREAD

**Issue by Brottweiler** [naelstrof/slop#70]
Somewhere after version `4.3.21`, slop gives the following error when executed on my Intel powered laptop, compared to my Nvidia powered desktop which does not have this issue. Slop worked fine in `4.3.21`, but then the archlinux package updated to `5.3.37`, and now slop fails with the following message.

```c
Slop encountered an error:
Failed to compile shader `#version 130
attribute vec2 position;
attribute vec2 uv;
varying vec2 uvCoord;
void main()
{
uvCoord = uv;
gl_Position = vec4(position,0,1);
}
`:
0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
```

Is the fix to simply disable OpenGL with the `-o` option, since GLSL 1.30 is not supported (on the laptop, I assume)?

**Comment by naelstrof** [comment]
Sorry for such a late response. It should be fixed with ee76d8e0dc3a63e54072f873c85f1403799dbf13

Let me know if it works for you!
