### ISSUE TITLE
Adjusting region with arrow keys no longer works

### ISSUE THREAD

**Issue by KeyboardFire** [naelstrof/slop#73]
In previous versions of `slop`, I could adjust the end of the selection opposite my mouse by using the arrow keys.

This no longer appears to work. Could this feature be added back?

**Comment by Brottweiler** [comment]
Seems like it was removed in the port over to wayland in https://github.com/naelstrof/slop/commit/4a7c5fe6fb87ded8aa75547e6da40cc331bbaeb9.

**Comment by naelstrof** [comment]
Sorry, I was trying to avoid any compatibility issues and code complexity. I'll add this when I can.

**Comment by naelstrof** [comment]
Meanwhile make sure you're using the [crosshair shader](https://camo.githubusercontent.com/a35ef1ddde56919f5c4961f62d67e1d5542a75e5/687474703a2f2f692e67697068792e636f6d2f327879306643324c4f4651666d2e676966)
 to increase accuracy on the first try.

**Comment by naelstrof** [comment]
Should be fixed with ccb020ce2984a44a98496d608f3a400cbd31c663

Let me know if it works for you, then I'll close.

**Comment by KeyboardFire** [comment]
Works for me - thanks!
