### ISSUE TITLE
Hard to find default path of saved image files

### ISSUE THREAD

**Issue by Ygarr** [naelstrof/slop#75]
With my light searches(also with strace tool) unable find where my image saved, and was it at all. "maim" behavior is can be as convenient, right example

**Comment by naelstrof** [comment]
slop doesn't create an image, maim doesn't actually either. You have to specify the filepath for maim to save or pipe it's output like so:

`maim blah.png`
`maim > blah.png`

**Comment by Ygarr** [comment]
Thank you for reply. Now it looks so:

┌————————(Sunday 23 April 2017 07:08:08 PM)-——(~) 
└> maim -s
No file specified, using /home/user/1492963725.png
┌————————(Sunday 23 April 2017 07:08:08 PM)-——(~) 
└> slop > image.jpg
 ┌————————(Sunday 23 April 2017 07:08:08 PM)-——(~) 
└> file   image.jpg
image.jpg: ASCII text

**Comment by onodera-punpun** [comment]
slop itself doesn't take screenshots, it only makes you make a selection and it will print the coordinates (in ASCII text form of course). Use `maim -s` to take selection screenshots, not `slop -s`.
