### ISSUE TITLE
maim -s uses a lot of cpu and heats up my laptop

### ISSUE THREAD

**Issue by tudurom** [naelstrof/slop#76]
![screenshot](https://ptpb.pw/WosG.png)

**Comment by naelstrof** [comment]
Ah yeah, that's because I don't have slop sleep ever. It's running as fast as possible. You're right that it probably shouldn't do that.

For now use the `--noopengl` flag, since it HAS to sleep to function properly: https://github.com/naelstrof/slop/blob/master/src/slop.cpp#L143

**Comment by naelstrof** [comment]
Should be fixed with 9b43427abcd2f6abb66e322fd18ce6a31f33bb74

Let me know how well it works for you.

**Comment by tudurom** [comment]
Fair enough. The CPU usage went down from 100% to 40%. At least it doesn't make my laptop sound like a jet engine.

**Comment by KeepBotting** [comment]
I encountered this as well. When running `maim --hidecursor -s shot.png` in [Manjaro ARM](https://manjaro.org/download/#ARM) on a [Pinebook Pro](https://wiki.pine64.org/index.php/Pinebook_Pro) it uses a lot of CPU.

Here is an [example](https://branon.me/files/NjQ2NjB.png), this lasts for as long as the cursor is in selection mode.

Adding `--noopengl` improves performance by [a lot](https://branon.me/files/ZjU3ZDk.png)

**Comment by naelstrof** [comment]
Yeah, I don't sleep in the opengl mode. I probably should implement that. Though if you're not using any of the opengl's shader features, --noopengl should work great for you.
