### ISSUE TITLE
How can I make a magnifier without warping

### ISSUE THREAD

**Issue by terlar** [naelstrof/slop#82]
I see the example which is a circle that has warping. I would like to have something similar to what was available earlier. Is it still possible to achieve something like this: http://naelstrof.com/articles/4

I have looked through the older revisions but having a hard time to wrap my head around the frag files and the older format.

**Comment by naelstrof** [comment]
You can adjust the `crosshair.frag` to just use linear scaling if you'd like. Though math and code is pretty scary so even I just made a new example for you to use here:

https://github.com/naelstrof/slop/blob/master/shaderexamples/boxzoom.frag

Good luck!

**Comment by terlar** [comment]
Thank you, this was tremendous help and thank you for a great tool.

**Comment by naelstrof** [comment]
I realized I should've been using the mix() function at [L47](https://github.com/naelstrof/slop/blob/master/shaderexamples/boxzoom.frag#L47),  you probably won't notice anything wrong unless your selection rectangle is transparent though.
