### ISSUE TITLE
printHelp prints an old/hard-coded version

### ISSUE THREAD

**Issue by primeos** [naelstrof/slop#83]
I just noticed that `slop --help` is still printing `slop v5.3.21` while the current version is `v6.3.46`.

It seems like that version is hard-coded:
```c++
void printHelp() {
    std::cout << "slop v5.3.21\n";
    std::cout << "\n";
```

I assume that function should actually use `SLOP_VERSION` like here: (`slop --version`):
```c++
    if ( version ) {
        std::cout << SLOP_VERSION << "\n";
        return 0;
    }
```

**Comment by naelstrof** [comment]
Nice catch, didn't notice because I just use the man-pages whenever I need to remember something.
It should be fixed now.
