### ISSUE TITLE
Making slop reproducible

### ISSUE THREAD

**Issue by D-Pow** [naelstrof/slop#89]
When CMake compiles files, it creates temporary directories to hold its files and logs those directory names in its log files, CMakeError.log and CMakeOutput.log (in the CMakeFiles directory). Slop could be reproducible if these two files were simply deleted after making. For more information about the importance of reproducible builds, read more [here](https://reproducible-builds.org/).

**Comment by AloisMahdal** [comment]
Just curious: can you point to part that says build logs should be removed?  I tried to look for it but most seems to consider *build environment*; how do logs fall into that?  I heard about reproducible builds and totally like the idea (I even try to roughly implement it in my own projects---they are actually noarch so should be an easy target) but frankly I would never think of *logs* to be part of that.
