### ISSUE TITLE
cxxopts::option_not_exists_exception on `slop -z`

### ISSUE THREAD

**Issue by AloisMahdal** [naelstrof/slop#92]
E.g.:

    @graphite:~$ slop -z
    terminate called after throwing an instance of 'cxxopts::option_not_exists_exception'
      what():  Option ‘z’ does not exist
    Aborted (core dumped)
    @graphite:~!134!$ 

OTOH:

    @graphite:~$ slop -?
    Slop encountered an error:
    Unexpected positional argument: -?
    @graphite:~!1!$

**Comment by winny-** [comment]
@AloisMahdal I think this issue was fixed by the above PR, let me know.

**Comment by AloisMahdal** [comment]
I certainly can't see the issue on `slop-7.4-9.fc32.x86_64`.

**Comment by AloisMahdal** [comment]
IOW, this is good to close.  Thanks!
