### ISSUE TITLE
command line arguments for shader

### ISSUE THREAD

**Issue by AUTplayed** [naelstrof/slop#97]
Hi, I'm a total noob at GLSL but I know some C. Is it possible to pass a command line argument to the shader? I'm imagining it like this:

`slop -r {shader} --arg {arg}`

and now in the .frag file:

```
void main(int argc, char *argv[]) { 
// do something with the argument
....
}
```

**Comment by naelstrof** [comment]
Currently there is not. You can jerry-rig up a script that quickly re-outputs a shader file with the correct arguments baked in, then load it dynamically into slop.

Alternatively, if you wanted some real-time variable that's not available by default. You can either add it [here](https://github.com/naelstrof/slop/blob/master/src/framebuffer.cpp#L93) or tell me about it and I might add it as a default myself.

**Comment by AUTplayed** [comment]
aw ok, I'll do it with a custom script that modifies the file. Thanks
