### ISSUE TITLE
make crash

### ISSUE THREAD

**Issue by pdeman** [naelstrof/slop#98]
Hi,

I tried to install slop but no success.
I installed dependencies:
apt-get install libglm-dev
apt-get install libglew-dev
apt-get install libxrender-dev

now the comande cmake -DCMAKE_INSTALL_PREFIX="/usr" ./ succeed

but when I type make:
slop/src/shader.hpp:32:21: fatal error: EGL/egl.h: no file or folder of this type.
compilation terminated.
CMakeFiles/slopy.dir/build.make:182 : la recette pour la cible « CMakeFiles/slopy.dir/src/slop.cpp.o » failed

Am i doing something wrong ?

**Comment by AloisMahdal** [comment]
You also need to install libegl-mesa-dev.

Notice that make mentions missing `EGL/egl.h`; you can search for it at [Debian package search][1]; that's how I found out the package name.

  [1]: https://packages.debian.org/search?searchon=contents&keywords=EGL%2Fegl.h&mode=path&suite=stable&arch=any

(There could be other requirements, just repeat the lookup.)

**Comment by pdeman** [comment]
thanks !
